version: '3'
services:
  web:
    container_name: myweb
    image: nginx
    ports:
      - "8080:80"
    networks: 
      - my-network
    environment:
      - CALCULATOR_URL=http://calculator:8081
  app:
    container_name: calculator
    build: .
    image: cal
    ports:
      - "8081:8081"
    networks: 
      - my-network
networks:
  my-network:
    driver: bridge